### ISSUE TITLE
conll2ske doesn't work on multiple files

### ISSUE THREAD

**Issue by arianna-bienati** [ellepannitto/conll2ske#3]
At the moment the package doesn't process the entire batch of conllu files I have at disposal, dunno why. 

It might be: 
- because of the argparse implementation missing the possibility to take directly directories as input. However, to keep code simpler, I wanted to avoid this option and just 'handle' this in the command line with a glob function. 
- because my files have some problems
- the function has been updated by gretchen, but I hadn't access to it and didn't want to disturb :)

**Comment by iiegn** [comment]
i don't think pure python can automagically do this... and so something like this will be necessary:
```python
if os.path.isfile(path):
    print("File : " + path)
if os.path.isdir(path):
    print("Directory : " + path)
```

**Comment by ellepannitto** [comment]
Sorry for my late reply.
@arianna-bienati do you think this could be what you were looking for? https://www.programming-books.io/essential/python/setting-mutually-exclusive-arguments-with-argparse-2fef841b30d04aa68b38f700fe3d830e
You can set a group of arguments to be mutually exclusive, and therefore take either an input directory and then glob over the contained files or a list of filenames as input :)

**Comment by arianna-bienati** [comment]
Hi guys! Thanks a lot for the input :)

So, actually my conllu files had some problems... now I fixed the problem in the files and tried our converter on them and they converted without issues.

My strategy for the argparse was to actually keep it the most simple as possible. To handle the selection of multiple files in a directory I simply used the nargs="+" and then passed `-i your_directory/*.conllu`. Everything works as expected. 

If you think that it would be more user-friendly to add mutually exclusive arguments (single file, list of filenames vs. directory), I can still try to implement it!

But just wanted to tell you that the problem was in the files and I spotted it ;) bacios!!

**Comment by ellepannitto** [comment]
Great :) 
We can add a validation step (by calling ud's validator script) if we want to release the package at some point :)

**Comment by arianna-bienati** [comment]
absolutely! I've written a validation script to spot this error, knowing a little bit the data. I need to make it nicer though ahah at the moment è un po' sketchy... I can take care of it and ask you for feedback to make it more generalizable :)

**Comment by ellepannitto** [comment]
We added validation from ud tools, see PR #6
